<?php

/**
 * @file
 * Contains evo_shared.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function evo_shared_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the evo_shared module.
    case 'help.page.evo_shared':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Shared components across features such as field bases') . '</p>';
      return $output;

    default:
  }
}
